# Generated by Django 2.2.1 on 2019-05-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='current',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
