# Generated by Django 2.2.1 on 2019-05-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0004_profilepic_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='current',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
