# Generated by Django 2.2.1 on 2019-05-25 12:17

import backend.common_helpers.update_filename
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0005_auto_20190524_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=backend.common_helpers.update_filename.update_filename_with_username)),
                ('current', models.BooleanField(blank=True, default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_profile.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
